EXECUTION_NOTIFICATION_ENABLED = env.bool("EXECUTION_NOTIFICATION_ENABLED", default=False)

FROM_EMAIL_NOTIFICATION = env.str("FROM_EMAIL_NOTIFICATION", default="")

SMTP_HOST_EMAIL_NOTIFICATION = env.str(
    "SMTP_HOST_EMAIL_NOTIFICATION", default=""
)

PASSWORD_EMAIL_NOTIFICATION = env.str("PASSWORD_EMAIL_NOTIFICATION", default="")