# Generated by Django 3.2.5 on 2021-07-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_engine', '0002_auto_20210730_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='functionservice',
            old_name='method',
            new_name='http_method',
        ),
    ]
