# Generated by Django 3.2.5 on 2021-08-01 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_engine', '0003_rename_method_functionservice_http_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionServiceEnvironmentVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=500)),
                ('function_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_engine.functionservice')),
            ],
            options={
                'db_table': 'function_service_environment_variable',
            },
        ),
    ]
