# Generated by Django 3.2.5 on 2022-01-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_engine', '0011_create_viewer_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionservice',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfunctionservice',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
