# Generated by Django 3.2.5 on 2022-01-10 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_engine', '0012_auto_20220110_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionServiceExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('request', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_engine.customer')),
                ('function_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_engine.functionservice')),
            ],
            options={
                'db_table': 'function_service_execution',
            },
        ),
    ]
