# Generated by Django 3.2.5 on 2022-03-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_engine', '0014_functionserviceexecution_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionservice',
            name='http_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POS', 'POST'), ('PUT', 'PUT'), ('DEL', 'DELETE')], default='GET', max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalfunctionservice',
            name='http_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POS', 'POST'), ('PUT', 'PUT'), ('DEL', 'DELETE')], default='GET', max_length=3),
        ),
    ]
