EXECUTION_STATUS_PENDING = "PE"
EXECUTION_STATUS_QUEUE = "QU"
EXECUTION_STATUS_PROCESSING = "PR"
EXECUTION_STATUS_SUCCESS = "SC"
EXECUTION_STATUS_ERROR = "ER"


EXECUTION_STATUS_CHOICE = (
    (EXECUTION_STATUS_PENDING, 'Pending'),
    (EXECUTION_STATUS_PROCESSING, 'Processing'),
    (EXECUTION_STATUS_SUCCESS, 'Success'),
    (EXECUTION_STATUS_ERROR, 'Error'),
    (EXECUTION_STATUS_QUEUE, 'Queue'),
)
