HTTP_METHOD_GET = "GET"
HTTP_METHOD_POST = "POS"
HTTP_METHOD_PUT = "PUT"
HTTP_METHOD_DELETE = "DEL"


HTTP_METHOD_CHOICE = (
    (HTTP_METHOD_GET, "GET"),
    (HTTP_METHOD_POST, "POST"),
    (HTTP_METHOD_PUT, "PUT"),
    (HTTP_METHOD_DELETE, "DELETE"),
)
