# Generated by Django 3.2.4 on 2021-07-02 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='action_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='action_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'action',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
            ],
            options={
                'db_table': 'script',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_status', models.IntegerField(choices=[('PE', 'Pending'), ('PR', 'Processing'), ('SC', 'Success'), ('ER', 'Error')], default='PE')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_engine.schedule')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='TicketActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_log', models.TextField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='task_engine.action')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_engine.ticket')),
            ],
            options={
                'db_table': 'ticket_action_log',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('execution_order', models.IntegerField(default=0)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_engine.action')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='step_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='steo_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_engine.schedule')),
            ],
            options={
                'db_table': 'step',
            },
        ),
        migrations.CreateModel(
            name='ScheduleExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_status', models.IntegerField(choices=[('PE', 'Pending'), ('PR', 'Processing'), ('SC', 'Success'), ('ER', 'Error')], default='PE')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_engine.schedule')),
            ],
            options={
                'db_table': 'schedule_execution',
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_engine.script'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.team'),
        ),
        migrations.AddField(
            model_name='action',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_engine.script'),
        ),
        migrations.AddField(
            model_name='action',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.team'),
        ),
    ]
