# Generated by Django 3.2.4 on 2021-07-02 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEnvironmentVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=500)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_engine.schedule')),
            ],
            options={
                'db_table': 'schedule_environment_variable',
            },
        ),
    ]
