# Generated by Django 3.2.5 on 2021-07-06 22:44

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleexecution',
            name='execution_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 7, 6, 22, 44, 7, 968094)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketactionlog',
            name='execution_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
