# Generated by Django 3.2.4 on 2021-07-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_engine', '0002_scheduleenvironmentvariable'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='cron_schedule',
            field=models.CharField(default='*', max_length=20),
            preserve_default=False,
        ),
    ]
