# Generated by Django 3.2.5 on 2021-07-26 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_engine', '0002_auto_20210706_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='schedule_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_engine.scheduleexecution'),
        ),
    ]
