# Generated by Django 3.2.5 on 2021-07-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_engine', '0003_ticket_schedule_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
