# Generated by Django 3.2.4 on 2021-07-03 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_engine', '0005_auto_20210703_2007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Step',
            new_name='StepSchedule',
        ),
        migrations.AlterModelTable(
            name='stepschedule',
            table='step_schedule',
        ),
        migrations.CreateModel(
            name='TicketParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=500)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_engine.ticket')),
            ],
            options={
                'db_table': 'ticket_parameter',
            },
        ),
    ]
