# Generated by Django 3.2.4 on 2021-07-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_engine', '0006_auto_20210703_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='execution_status',
            field=models.CharField(choices=[('PE', 'Pending'), ('PR', 'Processing'), ('SC', 'Success'), ('ER', 'Error')], default='PE', max_length=2),
        ),
    ]
