# Generated by Django 3.2.4 on 2021-07-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_engine', '0007_alter_ticket_execution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleexecution',
            name='execution_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleexecution',
            name='execution_status',
            field=models.IntegerField(choices=[('PE', 'Pending'), ('PR', 'Processing'), ('SC', 'Success'), ('ER', 'Error'), ('QU', 'Queue')], default='PE'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='execution_status',
            field=models.CharField(choices=[('PE', 'Pending'), ('PR', 'Processing'), ('SC', 'Success'), ('ER', 'Error'), ('QU', 'Queue')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='ticketactionlog',
            name='execution_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
