# Generated by Django 3.2.4 on 2021-07-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_engine', '0008_auto_20210703_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleexecution',
            name='execution_status',
            field=models.CharField(choices=[('PE', 'Pending'), ('PR', 'Processing'), ('SC', 'Success'), ('ER', 'Error'), ('QU', 'Queue')], default='PE', max_length=2),
        ),
    ]
