# Generated by Django 3.2.4 on 2021-07-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_engine', '0009_alter_scheduleexecution_execution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepschedule',
            name='stoppable',
            field=models.BooleanField(default=True),
        ),
    ]
