# Generated by Django 3.2.5 on 2021-10-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_engine', '0012_rename_created_date_ticket_created_date_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketparameter',
            name='value',
            field=models.TextField(),
        ),
    ]
