# Generated by Django 3.2.5 on 2022-05-15 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220331_2045'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_engine', '0015_alter_ticketparameter_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suffix_worker_name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('concurrency', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
            options={
                'db_table': 'team_worker',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTeamWorker',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('suffix_worker_name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('last_updated_date', models.DateTimeField(blank=True, editable=False)),
                ('concurrency', models.IntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.team')),
            ],
            options={
                'verbose_name': 'historical team worker',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
