# Generated by Django 3.2.5 on 2022-03-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicalteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalteam',
            name='slash_name',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='slash_name',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
