# Generated by Django 3.2.5 on 2022-03-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicalteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalteam',
            name='slash_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slash_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
